# Generated by Django 5.0.3 on 2024-04-17 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todoitem_remove_product_rate_alter_product_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
